### ISSUE TITLE
源码模式，怎么没法用jquery

### ISSUE THREAD

**Issue by tianxia0079** [webgjc/web_robot#2]
怎么启用jquery  确保页面有jquery

**Comment by webgjc** [comment]
@tianxia0079 

源码模式，点运行 使用的是chrome的  
chrome.tabs.executeScript ([https://developer.chrome.com/extensions/content_scripts#pi](https://developer.chrome.com/extensions/tabs#method-executeScript))

点开启注入使用的是 content script 的 
eval() ([https://developer.chrome.com/extensions/content_scripts#pi](https://developer.chrome.com/extensions/content_scripts#pi))

这两种js运行都是会在一个独立的环境(Work in Isolated Worlds)中，不能拿到页面js的变量和函数，只有document

官方说明如下：[https://developer.chrome.com/extensions/content_scripts#pi](https://developer.chrome.com/extensions/content_scripts#pi)
Isolated worlds do not allow for content scripts, the extension, and the web page to access any variables or functions created by the others. This also gives content scripts the ability to enable functionality that should not be accessible to the web page.

要确保源码执行可以有jquery变量和函数的话，
可以在manifest.json文件中直接单独把jquery引入进来
```
"content_scripts": [{
        "matches": ["<all_urls>"],
        "js": ["js/jquery.min.js", "js/content_script.js"]
}],
```
之后重新加载一次插件。

这个后续版本会优化掉。

**Comment by webgjc** [comment]
已支持
