### ISSUE TITLE
用js jquery自动化操作网页

### ISSUE THREAD

**Issue by tianxia0079** [webgjc/web_robot#3]
用js jquery自动化操作网页，可是现在dom不能及时更新，导致并没有按想象的流程操作，请问应该怎么优化？
还是说不能用这个思路自动化操作网页？

简单例子：
```
$("#kw").val("测试")
    sleep(2000)
    $("#su").click()
 sleep(2000)
        $(".s-top-img-wrapper").click()
//单位 毫秒
function sleep(d){
    for(var t = Date.now();Date.now() - t <= d;);
}
```

**Comment by webgjc** [comment]
@tianxia0079 
你指现在的流程是通过固定的延时来执行，不能确保触发的时候dom已经存在对吧，这个目前还没解决这个问题。

后续可以考虑设计一个事件的执行等待，等待事件的dom出现后在触发，不通过sleep固定时间。

**Comment by webgjc** [comment]
V1.9.0已支持dom自旋检查，确保存在dom在触发事件
