### ISSUE TITLE
关于input file

### ISSUE THREAD

**Issue by zy00000** [webgjc/web_robot#6]
小白弱弱的想问一下，页面上有一步需要上传图片，如果用click事件的话会弹出一个对话框，插件似乎不能对这个对话框进行操作，用value事件直接把值设成路径好像也没反应，那要怎么实现上传啊？

**Comment by webgjc** [comment]
关于上传这个的一些现状：
- 插件不能控制到点击上传弹出的文件选择框。
- 浏览器插件目前没有能读取到本地文件的权限。

目前可用的上传文件实现方法：
- 用插件里的 **受控事务** 这种方式，记录还原鼠标移动来实现  
（就不与浏览器dom元素相关，需开启插件里的python web服务）

像你说的知道文件路径实现上传：  
- 首先需要通过记录浏览器接口获取到这个上传的接口（手动操作一遍上传，可以用插件background监控接口获取到），  
- 插件调本地web服务，发出上传接口信息、header头(包括cookie)、和需要上传的文件路径。  
- 然后用本地python web实现一个上传接口，将本地的文件读取到并上传

**Comment by zy00000** [comment]
感谢回复~ 我去尝试一下
